name: Build Pre Release

on:
  workflow_dispatch:
    inputs:
  
jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8' 
     
    - name: Read tag_latest
      id: tag_latest
      shell: python
      run: |
        import re
        import os
        with open('src/nicelee/ui/Global.java', encoding='utf-8') as file:
            content = file.read()
            pattern = r'@Config\(key *= *"bilibili.version", *defaultValue *= *"v([\d\.]+)"'
            searchObj = re.search(pattern, content)
            with open(os.environ.get("GITHUB_OUTPUT"),'w', encoding='utf-8') as output:
                output.write("value=" + searchObj.group(1))
    
 
    - name: Package Jar
      run: |
        chmod +x package.sh
        ./package.sh

    - name: ZIP files
      run: |
        rm -rf ./config
        rm -rf ./LICENSE
        mkdir ./config/
        mkdir ./LICENSE/
        mv -f ./release/Create-Shortcut-on-Desktop-for-Linux.sh .
        mv -f ./release/Create-Shortcut-on-Desktop-for-Mac.sh .
        mv -f ./release/Create-Shortcut-on-Desktop-for-Win.vbs .
        mv -f ./release/Double-Click-to-Run-for-Mac.command .
        mv -f ./release/Double-Click-to-Run-for-Win.bat .
        mv -f ./release/Double-Click-to-Run-for-Win-debug.bat .
        mv -f ./release/uninstall.bat .
        mv -f ./release/update.bat .
        mv -f ./release/config/* ./config/
        mv -f ./release/LICENSE/* ./LICENSE/        
        
        zip BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip INeedBiliAV.jar
        zip -m BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip ./Create-Shortcut-on-Desktop-for-Linux.sh
        zip -m BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip ./Create-Shortcut-on-Desktop-for-Mac.sh
        zip -m BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip ./Create-Shortcut-on-Desktop-for-Win.vbs
        zip -m BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip ./Double-Click-to-Run-for-Mac.command
        zip -m BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip ./Double-Click-to-Run-for-Win.bat
        zip -m BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip ./Double-Click-to-Run-for-Win-debug.bat
        zip -m BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip ./uninstall.bat
        zip -m BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip ./update.bat
        zip -rm BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip ./config/
        zip -rm BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip ./LICENSE/
    
                  # wget https://github.com/nICEnnnnnnnLee/BilibiliDown/releases/download/V4.5/minimal-bilibilidown-jre11_win_x64.zip
                  # unzip minimal-bilibilidown-jre11_win_x64.zip
                  # cp BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip BilibiliDown.v${{steps.tag_latest.outputs.value}}.win_x64_jre11.pre-release.zip
                  # zip -rm BilibiliDown.v${{steps.tag_latest.outputs.value}}.win_x64_jre11.pre-release.zip ./minimal-bilibilidown-jre/

    - name: Upload artifacts(no jre)
      uses: actions/upload-artifact@v3
      with:
        name: BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release
        path: ./BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip
